name: Deploy to Dreamhost via SSH
on:
  push:
    branches:
    - main
permissions:
  actions: read
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Make sure the @v0.9.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DREAMHOST_SSH_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Build Vite site
        run: npm run build

      - name: Deploy to Dreamhost
        run: |
         ssh-keyscan -H iad1-shared-e1-14.dreamhost.com >> ~/.ssh/known_hosts
         scp -r ./dist/* dh_6uchux@iad1-shared-e1-14.dreamhost.com:/home/dh_6uchux/taskroulette.kilianrempen.com/
